[package]

name = "cobalt-bin"
version = "0.7.0"
authors = ["Benny Klotz <r3qnbenni@gmail.com>", "Johann Hofmann <mail@johann-hofmann.com>"]
description = "Static site generator written in Rust"
repository = "https://github.com/cobalt-org/cobalt.rs"
readme = "README.md"
keywords = ["static", "site", "generator"]
categories = ["command-line-utilities"]
license = "MIT"

[badges]
travis-ci = { repository = "cobalt-org/cobalt.rs" }
appveyor = { repository = "cobalt-org/cobalt.rs" }

[lib]
name="cobalt"

[[bin]]
name = "cobalt"
doc = false

[dependencies]
clap = "2.24"
liquid = {version = "0.10", features=["serde"]}
walkdir = "1.0"
yaml-rust = "0.3"
chrono = "0.3"
log = "0.3"
env_logger = "0.4"
rss = "0.3"
pulldown-cmark = "0.0.14"
notify = "4.0"
ghp = "0.1"
regex = "0.2"
clippy = {version = "0.0", optional = true}
error-chain = "0.10"
lazy_static = "0.2"
itertools = "0.5"
ignore = "0.2"
serde = "1.0"
serde_yaml = "0.7"

[dependencies.hyper]
version = "0.10"
default-features = false

[dependencies.syntect]
version = "1.5"
optional = true
default-features = false
features =  ["parsing", "assets", "html", "static-onig"]

[dev-dependencies]
assert_cli = "0.3"
lazy_static = "0.2"
difference = "1.0"
tempdir = "0.3"

[features]
default = []
unstable = []
dev = []

syntax-highlight = ["syntect"]

